development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: <%= ENV["POSTGRESQL_USER"] || ENV["USER"] || 'postgres' %>
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: <%= ENV["POSTGRESQL_USER"] || ENV["USER"] || 'postgres' %>
  password:
